version: "3.8"
services:
  dish-service-db:
    environment:
      - POSTGRES_PASSWORD=longpassword
      - POSTGRES_USER=user
      - POSTGRES_DB=dish-db
    image: postgres:14.0
    ports:
      - "7001:5432"

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=dish@mail.com
      - PGADMIN_DEFAULT_PASSWORD=longpassword
    image: dpage/pgadmin4
    ports:
      - "7101:80"

